import type { Metadata } from "next";
import { Geist, Azeret_Mono as Geist_Mono } from "next/font/google";
import "../../globals.css";
import Providers from "@/redux/Providers";
import { ToastContainer } from "react-toastify";
import { DashboardSidebar } from "@/components/layout/Sidebar/Sidebar";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { DashboardHeader } from "@/components/layout/Sidebar/partials/DashboardHeader";
import type React from "react"; // Import React

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Seller Mama",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-100 flex flex-col h-full`}
      >
        <Providers>
          <SidebarProvider>
            <div className="flex flex-grow overflow-hidden">
              <DashboardSidebar />
              <SidebarInset className="flex flex-col flex-grow w-full overflow-hidden">
                <DashboardHeader />
                <main className="flex-grow overflow-y-auto bg-muted/50 p-6">
                  {children}
                </main>
              </SidebarInset>
            </div>
          </SidebarProvider>
        </Providers>

        <ToastContainer
          position="top-center"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          draggable
          pauseOnHover
          theme="light"
        />
      </body>
    </html>
  );
}
